# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f29f4d30765f1559485adace08285226c1c87bf944e740918edbd825d6b5a44cf3ea26bd11482dec3c25fc8ae8561f957057d1ea122c571c3afa1b621378b05c

test:
  secret_key_base: 7d8921f2aa3407cb1f94284a635fd38060612724bdcff6864e12461dd3aff411e1d95b878e6b1f661c3f09f6def9e23448896c64ed07cb59d053aa7e998031ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
